// Static shell-completion scripts, generated by introspecting the live
// commander program at runtime (`kanban completion <shell>`), so the command
// and flag tables can never drift from the CLI. Kept out of kanban.ts, which
// parses argv at import time and therefore can't be imported from tests.
//
// Static only: no dynamic task-id completion (that would need a server
// round-trip per keystroke). See docs/05-cli-reference.md.
import type { Command } from 'commander';

export interface CmdSpec {
  name: string;
  options: string[];
  subs: CmdSpec[];
}

export type Shell = 'bash' | 'zsh' | 'pwsh';

export function normalizeShell(shell: string): Shell | null {
  const s = shell.toLowerCase();
  if (s === 'bash' || s === 'zsh' || s === 'pwsh') return s;
  if (s === 'powershell') return 'pwsh';
  return null;
}

export function specFromCommand(cmd: Command): CmdSpec {
  return {
    name: cmd.name(),
    options: (cmd as any).options.map((o: any) => o.long).filter(Boolean),
    subs: cmd.commands.map((c) => specFromCommand(c as Command)),
  };
}

/** Completion node: the words offered at one command path ('' = root). */
interface Node {
  key: string;
  words: string[]; // subcommand names + long flags
}

/** Flatten the spec into path-keyed nodes plus the set of group commands
 *  (commands that have subcommands, e.g. `dep`, `criterion`, `board`). */
function flatten(spec: CmdSpec): { nodes: Node[]; groups: string[] } {
  const nodes: Node[] = [];
  const groups: string[] = [];
  const walk = (c: CmdSpec, key: string) => {
    nodes.push({ key, words: [...c.subs.map((s) => s.name), ...c.options] });
    if (key && c.subs.length) groups.push(key);
    for (const s of c.subs) walk(s, key ? `${key} ${s.name}` : s.name);
  };
  walk(spec, '');
  return { nodes, groups };
}

export function renderCompletion(spec: CmdSpec, shell: Shell): string {
  const { nodes, groups } = flatten(spec);
  if (shell === 'pwsh') return pwshScript(spec.name, nodes, groups);
  if (shell === 'bash') return bashScript(spec.name, nodes, groups);
  return zshScript(spec.name, nodes, groups);
}

// The completion key is the first non-flag word, extended by the second one
// when the first is a group command. Extra positionals (titles, task ids)
// simply fail the lookup and complete to nothing — graceful degradation.

function pwshScript(name: string, nodes: Node[], groups: string[]): string {
  const table = nodes
    .map((n) => `    '${n.key}' = @(${n.words.map((w) => `'${w}'`).join(', ')})`)
    .join('\n');
  return `# ${name} PowerShell completion (static; regenerate with: ${name} completion pwsh)
# Install: ${name} completion pwsh | Out-String | Invoke-Expression
#   (or append that line to $PROFILE)
Register-ArgumentCompleter -Native -CommandName ${name} -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $table = @{
${table}
  }
  $groups = @(${groups.map((g) => `'${g}'`).join(', ')})
  $words = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })
  # Drop the word being completed (PS ranges descend, so guard the small cases).
  if ($wordToComplete) {
    if ($words.Count -le 1) { $words = @() } else { $words = @($words[0..($words.Count - 2)]) }
  }
  $path = @($words | Where-Object { $_ -notlike '-*' })
  $key = ''
  if ($path.Count -ge 1) { $key = $path[0] }
  if ($path.Count -ge 2 -and $groups -contains $key) {
    $k2 = "$key $($path[1])"
    if ($table.ContainsKey($k2)) { $key = $k2 }
  }
  if (-not $table.ContainsKey($key)) { return }
  $table[$key] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}
`;
}

function bashScript(name: string, nodes: Node[], groups: string[]): string {
  const cases = nodes
    .map((n) => `    "${n.key}") words="${n.words.join(' ')}" ;;`)
    .join('\n');
  return `# ${name} bash completion (static; regenerate with: ${name} completion bash)
# Install: ${name} completion bash > ~/.local/share/bash-completion/completions/${name}
#   (or: eval "$(${name} completion bash)" in ~/.bashrc)
_${name}() {
  local cur key groups words w i p1 p2
  cur="\${COMP_WORDS[COMP_CWORD]}"
  groups=" ${groups.join(' ')} "
  p1="" p2=""
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="\${COMP_WORDS[i]}"
    [[ "$w" == -* ]] && continue
    if [[ -z "$p1" ]]; then p1="$w"; elif [[ -z "$p2" ]]; then p2="$w"; fi
  done
  key="$p1"
  if [[ -n "$p2" && "$groups" == *" $p1 "* ]]; then key="$p1 $p2"; fi
  words=""
  case "$key" in
${cases}
  esac
  COMPREPLY=( $(compgen -W "$words" -- "$cur") )
}
complete -F _${name} ${name}
`;
}

function zshScript(name: string, nodes: Node[], groups: string[]): string {
  const cases = nodes
    .map((n) => `    "${n.key}") completions=(${n.words.join(' ')}) ;;`)
    .join('\n');
  return `#compdef ${name}
# ${name} zsh completion (static; regenerate with: ${name} completion zsh)
# Install: ${name} completion zsh > ~/.zsh/completions/_${name}  (with that dir on $fpath)
_${name}() {
  local -a completions path
  local key w p1 p2
  local groups=" ${groups.join(' ')} "
  for w in \${words[2,CURRENT-1]}; do
    [[ "$w" == -* ]] && continue
    if [[ -z "$p1" ]]; then p1="$w"; elif [[ -z "$p2" ]]; then p2="$w"; fi
  done
  key="$p1"
  if [[ -n "$p2" && "$groups" == *" $p1 "* ]]; then key="$p1 $p2"; fi
  completions=()
  case "$key" in
${cases}
  esac
  (( \${#completions} )) && compadd -- \${completions[@]}
}
_${name} "$@"
`;
}
